### ISSUE TITLE
ensuse in a test that there is no property that is unsorted

### ISSUE THREAD

**Issue by jstavel** [Differ-GSOC/differ#3]
Each property should be handled some way.

Someone is ignored, other one is ignored.

Noone can be unhandled.

So, please check that list of unhandled properties is empty.

**Comment by jonatansve** [comment]
Can you please clarify this issue. 

This is what I'm doing currently:
A. Properties from transformed metadata (ALL) should be checked to be in image14Test01RecognizedProperties.

B. Above properties from transformed metadata should have the same value as in image14significantProperties. 

C. ignoredProperties do not appear in transformed metadata. 

Now, are you saying that the metadata list metadataSignificantProperties.xml, all of these properties, should be in either image14Test01RecognizedProperties OR image14Test01IgnoredProperties. Otherwise, they are "unhandled"? In that case I'll run another test making sure this is true. 

 If you mean that each property from transformed metadata should be handled, well this is asserted in (A).

 If none of the above is the case, please elaborate!

**Comment by jstavel** [comment]
I do not know what you mean:
 Otherwise, they are "unhandled"? In that case I'll run another test making sure this is true.

We have to ensure that all properties the transformer returns are processed.
The property is either in the significant list or in the ignored properties list.

If it is neither of the lists, it is wrong and test failed.

**Comment by jonatansve** [comment]
Like I said above, each entry in transformed metadata is asserted to be in the significant values list, the exact line is this one:

https://github.com/Differ-GSOC/differ/blob/jpylyzer-unittest/differ-cmdline/src/test/java/cz/nkp/differ/cmdline/JpylyzerUnitTest.java#L57

Right now, all the values that are outputted by transformed metadata are in the list. 
Ignored values are the ones that do not appear in jpylyzer output. 

You say that the transformed metadata must be in either of the lists. Can you tell me which of the significant properties should be on the ignored metadata list? As I stated, the ones that are not recognized are there now.

**Comment by jstavel** [comment]
Ignored list can be empty. It means that all properties the transformer provides are important for us.

Great job.
Jan
